name = "tiffy-app"
main = "dist/server/index.mjs"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "test-kv-namespace"
preview_id = "test-kv-namespace"

[[d1_databases]]
binding = "DB"
database_name = "tiffy-db"
database_id = "test-d1-database"

[[r2_buckets]]
binding = "BLOB"
bucket_name = "tiffy-blob"
