name = "tiffy-app"
main = "dist/server/index.mjs"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "8fba5729163846f0967492f6b31c30af"
preview_id = "8fba5729163846f0967492f6b31c30af"

[[d1_databases]]
binding = "DB"
database_name = "tiffy-db"
database_id = "6edcf829-b7ca-4694-8f55-1d40b940ed7f"
migrations_dir = "dist/database/migrations"

[[r2_buckets]]
binding = "BLOB"
bucket_name = "tiffy-blob"
